---
- name: Create nginx-proxy directory
  file:
    path: "{{ nginx_proxy_dir }}"
    state: directory
    mode: '0755'

- name: Copy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ nginx_proxy_dir }}/docker-compose.yml"

- name: Start nginx-proxy stack
  command: docker compose -f {{ nginx_proxy_dir }}/docker-compose.yml up -d
